# 日志级别配置
logging:
  level:
    cn.itcast: debug

# 服务端口
server:
  port: 8088

# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yun6
    username: root
    password: root

# mybatis
mybatis:
  type-aliases-package: cn.itcast.pojo
  #config-location: mapper/*.xml